name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Genere tous les jours a minuit
  workflow_dispatch:     # Permet de lancer manuellement depuis GitHub Actions

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Génère le Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: DIARY7
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push vers la branche output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
